# -*- coding: utf-8 -*-
"""Stock Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1T-ARMCZw9IHDuyGlk1dy-qYmAWiuIn
"""

import yfinance as yf
import pandas as pd
import datetime
import sys

def get_stock_data(ticker_symbol):
    """
    Fetches real-time and historical data for a given ticker.
    """
    print(f"Fetching data for {ticker_symbol}...")
    stock = yf.Ticker(ticker_symbol)

    # Get Fundamental Info
    info = stock.info

    # Get Historical Data (1 Year for moving averages)
    hist = stock.history(period="1y")

    if hist.empty:
        print(f"Error: No data found for ticker '{ticker_symbol}'")
        return None, None

    return info, hist

def calculate_technicals(df):
    """
    Calculates technical indicators: SMA, RSI, Volatility.
    """
    # Simple Moving Averages
    df['SMA_50'] = df['Close'].rolling(window=50).mean()
    df['SMA_200'] = df['Close'].rolling(window=200).mean()

    # RSI Calculation (14-day)
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()

    # Avoid division by zero
    loss[loss == 0] = 0.001
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))

    return df

def analyze_valuation(info, current_price):
    """
     performs basic quantitative valuation analysis.
    """
    analysis = {}

    # 1. P/E Ratio Analysis
    pe = info.get('trailingPE')
    forward_pe = info.get('forwardPE')
    sector_pe = 20 # Approximate generic sector PE for comparison

    if pe:
        if pe < 15: analysis['P/E Verdict'] = "Undervalued (Low P/E)"
        elif pe > 30: analysis['P/E Verdict'] = "Overvalued (High P/E)"
        else: analysis['P/E Verdict'] = "Fair Value"
    else:
        analysis['P/E Verdict'] = "N/A (No Earnings)"

    # 2. Price vs 52 Week High
    high_52 = info.get('fiftyTwoWeekHigh', current_price)
    discount = ((high_52 - current_price) / high_52) * 100
    analysis['Discount from High'] = f"{discount:.2f}%"

    # 3. Peg Ratio (Growth check)
    peg = info.get('pegRatio')
    if peg:
        if peg < 1: analysis['PEG Verdict'] = "Undervalued (PEG < 1)"
        elif peg > 2: analysis['PEG Verdict'] = "Overvalued (PEG > 2)"
        else: analysis['PEG Verdict'] = "Fair Price for Growth"

    return analysis

def main():
    print("--- Automated Stock Analysis Tool ---")
    ticker = input("Enter Stock Ticker (e.g., AAPL, NVDA): ").upper()

    try:
        info, hist = get_stock_data(ticker)
        if info is None: return

        # Perform Calculations
        hist_processed = calculate_technicals(hist)
        current_price = info.get('currentPrice', hist['Close'].iloc[-1])

        # Valuation
        valuation = analyze_valuation(info, current_price)

        # --- OUTPUT REPORT ---
        print("\n" + "="*40)
        print(f" QUANTITATIVE REPORT: {ticker}")
        print("="*40)

        print(f"\n[REAL-TIME DATA]")
        print(f"Price:        ${current_price:.2f}")
        print(f"Market Cap:   {info.get('marketCap', 'N/A'):,}")
        print(f"Beta (Vol):   {info.get('beta', 'N/A')}")

        print(f"\n[TECHNICAL INDICATORS]")
        last_row = hist_processed.iloc[-1]
        print(f"RSI (14-day): {last_row['RSI']:.2f} ({'Oversold' if last_row['RSI']<30 else 'Overbought' if last_row['RSI']>70 else 'Neutral'})")
        print(f"50-Day SMA:   ${last_row['SMA_50']:.2f}")
        print(f"200-Day SMA:  ${last_row['SMA_200']:.2f}")

        trend = "BULLISH" if last_row['SMA_50'] > last_row['SMA_200'] else "BEARISH"
        print(f"Trend:        {trend} (Golden/Death Cross Check)")

        print(f"\n[VALUATION METRICS]")
        print(f"Trailing P/E: {info.get('trailingPE', 'N/A')}")
        print(f"Forward P/E:  {info.get('forwardPE', 'N/A')}")
        print(f"PEG Ratio:    {info.get('pegRatio', 'N/A')}")
        print(f"Div Yield:    {info.get('dividendYield', 0)*100:.2f}%")

        print(f"\n[AUTOMATED VERDICTS]")
        for k, v in valuation.items():
            print(f"- {k}: {v}")

        print("\n" + "="*40)
        print("Done. To save this to Excel, you can use pandas: df.to_excel('report.xlsx')")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
